#!/bin/sh

if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
  echo "usage: $0 [key] query"
  exit -1
fi

if [ "$#" -eq 1 ]; then
  query=$1
fi

if [ "$#" -eq 2 ]; then
  query=$1":"$2
fi

open -g "dash://$query"
